language: go

go:
  - 1.5
  - 1.6

env:
  global:
    - GO15VENDOREXPERIMENT=1
    - TRACEVIEW_DEBUG=1
        
install:
  - wget https://files.appneta.com/install_appneta.sh
  - sudo sh ./install_appneta.sh f08da708-7f1c-4935-ae2e-122caf1ebe31
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  - go get golang.org/x/net/context github.com/stretchr/testify/assert gopkg.in/mgo.v2/bson

script:
  - env
  - cd $GOPATH/src/github.com/$TRAVIS_REPO_SLUG/v1/tv
  - go build -v github.com/$TRAVIS_REPO_SLUG/v1/tv github.com/$TRAVIS_REPO_SLUG/v1/tv/internal/traceview
  - go test -v -covermode=atomic -coverprofile=cov.out -coverpkg github.com/$TRAVIS_REPO_SLUG/v1/tv/internal/traceview,github.com/$TRAVIS_REPO_SLUG/v1/tv
  - go test -v -tags traceview -covermode=atomic -coverprofile=covtv.out -coverpkg github.com/$TRAVIS_REPO_SLUG/v1/tv/internal/traceview,github.com/$TRAVIS_REPO_SLUG/v1/tv
  - pushd internal/traceview/
  - go test -v -covermode=atomic -coverprofile=cov.out
  - go test -v -tags traceview -covermode=atomic -coverprofile=covtv.out
  - popd
  - gocovmerge cov.out covtv.out internal/traceview/cov.out internal/traceview/covtv.out > covmerge.out
  - $GOPATH/bin/goveralls -coverprofile=covmerge.out -service=travis-ci
